### ISSUE TITLE
cross compile

### ISSUE THREAD

**Issue by sinkevichmm** [hidez8891/shm#1]
Good afternoon! I can not compile
from Lubuntu 17.10
to env GOARCH=arm GOOS=linux go build
ERR:
../github.com/hidez8891/shm/shm.go:10:7: undefined: shmi

go version go1.10.1 linux/386

**Comment by hidez8891** [comment]
I have not tested GOARCH=arm.

According to this [gist](https://gist.github.com/steeve/6905542), you need to set env CC and CGO_ENABLED.
```
$ CC=arm-linux-gnueabihf-gcc GOOS=linux GOARCH=arm CGO_ENABLED=1 go build -ldflags="-extld=$CC"
```
